config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :almuerzos
  get 'registrar/usuarios'
  get 'login/logueo'
  get 'welcome/index'

  root 'welcome#index'

end

app/models/almuerzo.rb
class Almuerzo < ActiveRecord::Base
	validates :foto, presence:true
	validates :nombre, presence:true, uniqueness:true
	validates :descripcion, presence:true, length:{ minunum: 10, maximum:100}
	validates :precio, presence:true, numericality:{greater_than: 0, only_integer:true} 
	validates :stock, presence:true, numericality:{greater_than: 0, only_integer:true}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :nombre, presence:true
  validates :phone, presence:true, numericality:{greater_than: 0, only_integer:true}
  validates :tienda, presence:true

end

app/controllers/almuerzos_controller.rb
class AlmuerzosController < ApplicationController
  before_action :set_almuerzo, only: [:show, :edit, :update, :destroy]
  # filtrando contenido al usario
  before_filter :authenticate_user!, except:[ :index ]

  # GET /almuerzos
  # GET /almuerzos.json
  def index
    @almuerzos = Almuerzo.all
  end

  # GET /almuerzos/1
  # GET /almuerzos/1.json
  def show
  end

  # GET /almuerzos/new
  def new
    @almuerzo = Almuerzo.new
  end

  # GET /almuerzos/1/edit
  def edit
  end

  # POST /almuerzos
  # POST /almuerzos.json
  def create
    @almuerzo = Almuerzo.new(almuerzo_params)

    respond_to do |format|
      if @almuerzo.save
        format.html { redirect_to @almuerzo, notice: 'Almuerzo creado con exito.' }
        format.json { render :show, status: :created, location: @almuerzo }
      else
        format.html { render :new }
        format.json { render json: @almuerzo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /almuerzos/1
  # PATCH/PUT /almuerzos/1.json
  def update
    respond_to do |format|
      if @almuerzo.update(almuerzo_params)
        format.html { redirect_to @almuerzo, notice: 'Almuerzo actualizado con exito.' }
        format.json { render :show, status: :ok, location: @almuerzo }
      else
        format.html { render :edit }
        format.json { render json: @almuerzo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /almuerzos/1
  # DELETE /almuerzos/1.json
  def destroy
    @almuerzo.destroy
    respond_to do |format|
      format.html { redirect_to almuerzos_url, notice: 'Almuerzo eliminado con exito.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_almuerzo
      @almuerzo = Almuerzo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def almuerzo_params
      params.require(:almuerzo).permit(:foto, :nombre, :descripcion, :precio, :stock)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up){ |u| u.permit(:email,:tienda,:phone,:nombre,:password,:password_confirmation)}
    devise_parameter_sanitizer.permit(:account_update){ |u| u.permit(:email,:tienda,:phone,:nombre,:password,:current_password)}
  end

end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def logueo
  end
end

app/controllers/registrar_controller.rb
class RegistrarController < ApplicationController
  def usuarios
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/almuerzos_helper.rb
module AlmuerzosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/registrar_helper.rb
module RegistrarHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/almuerzos/_form.html.erb
<%= form_for(@almuerzo) do |f| %>
  <% if @almuerzo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@almuerzo.errors.count, "error") %> prohibited this almuerzo from being saved:</h2>

      <ul>
      <% @almuerzo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<!-- Formulario de creacion de menu -->
<div class="form-group">
  <div class="field">
    <%= f.label :foto %><br>
    <%= f.text_field :foto , :class => 'form-control', :placeholder => 'Url del Almuerzo' %>
  </div>
  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre, :class => 'form-control', :placeholder => 'Nombre del Almuerzo' %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_area :descripcion, :class => 'form-control', :placeholder => 'Descripcion del Almuerzo'%>
  </div>
  <div class="field">
    <%= f.label :precio %><br>
    <%= f.number_field :precio, :class => 'form-control',:placeholder => 'Precio del Almuerzo' %>
  </div>
  <div class="field">
    <%= f.label :stock %><br>
    <%= f.number_field :stock, :class => 'form-control', :placeholder => 'Stock del Almuerzo' %>
  </div>
  <div class="actions">
    <%= f.submit "Crear", :class =>' btn btn-primary' %>
  </div>
</div>

<% end %>

app/views/almuerzos/edit.html.erb
<!-- vista editar menu -->

 <!-- titulo  -->
<div class="container">
	<div class="thumbnail">
		<h1>Editar Almuerzo</h1>
	</div>
</div>

<!-- Formulario -->	
<div class=" container">
	<div class="thumbnail">
		<%= render 'form' %>
	</div>
	<!-- boton volver y show  -->
	<button type="button" class="btn">
			<%= link_to 'Show', @almuerzo %> |
			<%= link_to 'Volver', almuerzos_path %>
	</button>		
</div>	

app/views/almuerzos/index.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron">
  <div class="container">
    <h1>Listado de Almuerzos</h1>
  </div>  
</div>
  
  <% @almuerzos.each do |almuerzo| %>
    <div class= "container">
     <div class="col-md-4"> 
       <div class= "thumbnail">
        <h2> <%= almuerzo.nombre %> </h2>
        <%= image_tag(almuerzo.foto, :class => 'img-responsive') %>
        <p> <strong> Menú: </strong> <%= almuerzo.descripcion %> </p>
        <p> <strong> Precio: </strong> $<%= almuerzo.precio %> </p>
        <p> <strong> Stock: </strong> <%= almuerzo.stock %> unidades </p>
          
          <!-- Validando botones  -->
          <% if user_signed_in? %> 
          <button type="button" class="btn"> 
            <%= link_to 'Show', almuerzo %>
          </button>  
          <button type="button" class="btn">
            <%= link_to 'Editar Menú', edit_almuerzo_path(almuerzo) %>
          </button>
          <button type="button" class="btn">
            <%= link_to 'Eliminar Menú', almuerzo, method: :delete, data: { confirm: 'Estas seguro?' } %>
          </button>
          <% end %>

     </div>
    </div>       

    <% end %>
<br>
  <!-- validando botones  -->
  <% if user_signed_in? %> 
  <button type="button" class="btn"> 
    <%= link_to 'Crear nuevo Almuerzo', new_almuerzo_path %>
  </button>
  <% end %> 

app/views/almuerzos/new.html.erb
<!-- vista crear nuevo almuerzo -->

<!-- titulo  -->
<div class="container">
	<div class="thumbnail">
		<h1>Crear nuevo Almuerzo</h1>
	</div>
</div>

<!-- Formulario  -->
<div class=" container">	
	<div class="thumbnail">
		<%= render 'form' %>	
 	</div >
 	<!-- boton volver -->
 	<button type="button" class="btn">
		<%= link_to 'Volver', almuerzos_path %>
	</button>
</div>

app/views/almuerzos/show.html.erb
<!-- vista show  -->
<p id="notice"><%= notice %></p>

<dev class="container">
  <dev class="thumbnail">
   <p>
      <strong>Foto:</strong>
       <%= image_tag (@almuerzo.foto) %>
    </p>

    <p>
      <strong>Nombre:</strong>
      <%= @almuerzo.nombre %>
    </p>

    <p>
      <strong>Descripcion:</strong>
      <%= @almuerzo.descripcion %>
    </p>

    <p>
      <strong>Precio:</strong>
      <%= @almuerzo.precio %>
    </p>

    <p>
      <strong>Stock:</strong>
      <%= @almuerzo.stock %>
    </p>
  </dev> 
</dev>

<button type="button" class="btn">
  <%= link_to 'Editar', edit_almuerzo_path(@almuerzo) %> |
  <%= link_to 'Volver', almuerzos_path %>
</button>

app/views/compartidos/_navbar.html.erb
<!-- Navbar pills -->
<ul class="nav nav-pills">
	<li role="presentation"><a href='<%=root_path=%>'>Inicio</a></li>
  <li role="presentation"><a href='<%=almuerzos_path=%>'>Almuerzos</a></li>
  <% if user_signed_in? %> 
  <li role="presentation"><a href="<%= edit_user_registration_path %>">Perfil</a></li>
  <% end %>

	<!-- Navbar pills Al lado derecho  -->
  <ul class="nav nav-pills navbar-right">
			<!-- if login y logout  -->
		<% if current_user.nil? %>
			<li role="presentation"><a href="<%= new_user_session_path %>">Iniciar sesion</a></li>
  		<li style="padding-right: 16px" role="presentation"><a href= "<%= new_user_registration_path %>">Registrarse</a></li>
  	<% else %>
  		<li style="padding-right: 16px" role="presentation"> <a href="<%= destroy_user_session_path %>" data-method= "delete">Salir</a>
  		</li>
  	<% end %>	
	</ul>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Almuerzos-Flash</title>
  
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</head>

<body>
	<!-- Llamando al Navbar desde la carpeta compartidos -->
	<%= render 'compartidos/navbar'%>
    <!-- devise  -->
	 <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>



	<%= yield %>

</body>
</html>

app/views/login/logueo.html.erb
<h1>Login#logueo</h1>
<p>Find me in app/views/login/logueo.html.erb</p>

app/views/registrar/usuarios.html.erb
<h1>Registrar#usuarios</h1>
<p>Find me in app/views/registrar/usuarios.html.erb</p>

app/views/welcome/index.html.erb
<!-- jumbotron 1 -->
<div id="jumbotron1" class="jumbotron">
  <div class="container"> 
  	<h1>Almuerzos Easton Mall</h1>
  	<h3>El placer de la variedad en tu plato</h3>
  	<p><a class="btn btn-primary btn-lg" href="<%= new_user_registration_path %>" role="button">Registrate</a></p>
  </div>
</div>

<!-- dividiendo la pagina en 4 columnas -->
<div class= "container">
  <div class="row">
    <!-- columna 1 -->
  	<div class="col-md-4">
      <div class="page-header">
  		  <h1>Example page header <small>Subtext for header</small></h1>
  				Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
  				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
  				quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
  				consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
  				cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
  				proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  		</div>	
    </div>
    <!-- columna 2 -->
    <div class="col-md-4">
      <div class="page-header">
        <h1>Example page header <small>Subtext for header</small></h1>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
          cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
          proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </div>  
    </div>
    <!-- columna 3 -->
    <div class="col-md-4">
      <div class="page-header">
        <h1>Example page header <small>Subtext for header</small></h1>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
          cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
          proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </div>  
    </div>
    
  </div>

</div>